# Generated by Django 5.1.4 on 2025-01-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientProfile',
            new_name='Patient',
        ),
    ]
