# Generated by Django 5.1.4 on 2025-01-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='video',
        ),
    ]
