# Generated by Django 5.1.4 on 2025-01-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_message_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='qualifications',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualifications_en',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualifications_ru',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
