# Generated by Django 5.1.4 on 2025-01-06 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_doctor_qualifications_doctor_qualifications_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualifications',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualifications_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualifications_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_doctor', to='system.departments'),
        ),
    ]
