# Generated by Django 5.1.4 on 2025-01-06 14:40

import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_departments_address_en_departments_address_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG'),
        ),
        migrations.AddField(
            model_name='departments',
            name='working_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('пн', 'пн'), ('вт', 'вт'), ('ср', 'ср'), ('чт', 'чт'), ('пт', 'пт'), ('сб', 'сб'), ('вс', 'вс'), ('круглосуточно', 'круглосуточно')], max_length=16, null=True),
        ),
    ]
