# Generated by Django 5.1.4 on 2025-01-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_departments_phone_number_departments_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
