# Generated by Django 5.1.4 on 2025-01-06 19:16

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_departments_shift_end_departments_shift_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='working_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('пн', 'пн'), ('вт', 'вт'), ('ср', 'ср'), ('чт', 'чт'), ('пт', 'пт'), ('сб', 'сб'), ('вс', 'вс'), ('круглосуточно', 'круглосуточно')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualifications',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualifications_en',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualifications_ru',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
