# Generated by Django 5.1.4 on 2025-01-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_departments_working_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
