# Generated by Django 5.1.4 on 2025-01-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_departments_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
