# Generated by Django 5.1.4 on 2025-01-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_departments_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='prescribed_medication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
